services:
  database_inventoria:
    image: database_inventoria
    build: 
      context: ./databases/
    ports: 
      - "5432:5432"
    volumes:
      - ./databases/data:/var/lib/postgresql/data
  backend_inventoria:
    image: backend_inventoria
    build: 
      context: ./
    ports: 
      - "8080:8080"
    depends_on:
      - database_inventoria